show = true

[number]
	x = -60
	y = 100
	#Range: 0.0 ~ 10.0
	scale = 2.5
	#Range: 0.0 ~ 1.0
	opacity = 1.0
	show = true

[title]
	x = 10000
	y = 75
	#Range: 0.0 ~ 10.0
	scale = 1.7999999523162842
	#Range: 0.0 ~ 1.0
	opacity = 1.0
	show = true

[combo]
	x = -60
	y = 90
	#Range: 0.0 ~ 1.0
	opacity = 1.0
	#Range: 0.0 ~ 10.0
	scale = 1.2000000476837158
	show = true

[damage_list]
	x = -40
	y = 120
	#Range: 0.0 ~ 1.0
	opacity = 1.0
	#Range: 0.0 ~ 10.0
	scale = 0.800000011920929
	max_size = 10
	show = true

[damage_rank]
	#Use damage ranked style
	enable = false
	#Use format like "<damage amount>|<rank name>|<render color>"
	option = ["0|D|16777215", "20|C|15138811", "50|B|12249087", "100|A|12248631", "200|S|16774502", "400|SS|16759702", "800|SSS|16753566"]

	[damage_rank.color]
		#Color the damage number
		number = true
		#Color the title
		title = true
		#Color the title
		combo = true

[combo_rank]
	#Use combo ranked style
	enable = false
	#Use format like "<combo>|<rank name>|<render color>"
	option = ["0|D|16777215", "5|C|15138811", "10|B|12249087", "20|A|12248631", "40|S|16774502", "80|SS|16759702", "160|SSS|16753566"]

	[combo_rank.color]
		#Color the damage number
		number = true
		#Color the title
		title = true
		#Color the combo
		combo = true

